# Generated by Django 6.0 on 2026-01-06 19:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_fechamento', models.IntegerField(help_text='Dia que a fatura fecha')),
                ('dia_vencimento', models.IntegerField(help_text='Dia que você paga')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('eh_essencial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateField(default=django.utils.timezone.now)),
                ('eh_cartao', models.BooleanField(default=False)),
                ('qtd_parcelas', models.IntegerField(default=1)),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.cartaocredito')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.transacao')),
            ],
        ),
    ]
