# Generated by Django 6.0 on 2026-01-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='eh_pagamento_fatura',
            field=models.BooleanField(default=False),
        ),
    ]
