# Generated by Django 6.0 on 2026-01-06 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_vencimento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('eh_fixa', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='eh_essencial',
        ),
        migrations.AddField(
            model_name='categoria',
            name='teto_mensal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sua meta de gastos para esta categoria', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='dia_fechamento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='dia_vencimento',
            field=models.IntegerField(),
        ),
    ]
